'use client';

import { useState, useEffect } from 'react';
import { Plus, Eye, Heart, MessageCircle, ExternalLink, Instagram, Youtube, Loader2 } from 'lucide-react';
import { Card, CardContent } from '@/components/ui';
import { Button } from '@/components/ui';
import { formatNumber } from '@/lib/utils';
import { useRouter } from 'next/navigation';
import { postService } from '@/services/post.service';

// The `/posts/me/list` endpoint returns published-post records generated by the
// campaign "publish now" flow, not the marketplace `Post` shape from post.types.ts.
interface MyPublishedPost {
  id: string;
  creatorUserId: string;
  campaignId: string;
  scheduledPostId: string;
  platform: string;
  title: string;
  content: string;
  media: string[];
  platformPostUrl: string;
  views: number;
  likes: number;
  comments: number;
  publishedAt: string;
}

const platformIcon = (platform: string) => {
  if (platform === 'YOUTUBE') return <Youtube className="h-3.5 w-3.5" />;
  return <Instagram className="h-3.5 w-3.5" />;
};

export default function MyPostsPage() {
  const router = useRouter();
  const [posts, setPosts] = useState<MyPublishedPost[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<'all' | string>('all');

  useEffect(() => {
    postService
      .getMyPosts()
      .then((res: any) => setPosts(res.items ?? []))
      .catch(() => setError('Failed to load posts. Please try again.'))
      .finally(() => setIsLoading(false));
  }, []);

  const platforms = Array.from(new Set(posts.map(p => p.platform)));
  const filtered = filter === 'all' ? posts : posts.filter(p => p.platform === filter);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-foreground">My Posts</h1>
          <p className="text-muted-foreground mt-1">Manage and track your content across all platforms</p>
        </div>
        <Button variant="brand" onClick={() => router.push('/dashboard/creative/content/new')}>
          <Plus className="h-4 w-4 mr-2" />
          Create New Post
        </Button>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 p-3 rounded-lg text-sm">
          {error}
        </div>
      )}

      {/* Summary cards */}
      <div className="grid grid-cols-2 lg:grid-cols-3 gap-4">
        {[
          { label: 'Total Posts', value: posts.length },
          { label: 'Total Views', value: formatNumber(posts.reduce((s, p) => s + p.views, 0)) },
          { label: 'Total Likes', value: formatNumber(posts.reduce((s, p) => s + p.likes, 0)) },
        ].map(s => (
          <Card key={s.label}>
            <CardContent className="pt-5">
              <p className="text-xs text-muted-foreground">{s.label}</p>
              <p className="text-2xl font-bold mt-1">{s.value}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Filter tabs */}
      {platforms.length > 0 && (
        <div className="flex gap-2">
          {(['all', ...platforms] as const).map(f => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-4 py-1.5 rounded-full text-sm font-medium capitalize transition-colors ${
                filter === f
                  ? 'bg-brand-blue text-white'
                  : 'bg-muted text-muted-foreground hover:text-foreground'
              }`}
            >
              {f.toLowerCase()}
            </button>
          ))}
        </div>
      )}

      {/* Posts list */}
      {isLoading ? (
        <div className="flex items-center justify-center py-16 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin mr-2" />
          Loading posts...
        </div>
      ) : filtered.length === 0 ? (
        <div className="text-center py-16 text-muted-foreground">
          No posts yet. Published campaign content will appear here.
        </div>
      ) : (
        <div className="space-y-3">
          {filtered.map(post => (
            <Card key={post.id}>
              <CardContent className="py-4">
                <div className="flex flex-col sm:flex-row sm:items-center gap-4">
                  {/* Left */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className="font-semibold text-foreground">{post.title}</span>
                      <span className="inline-flex items-center gap-1 text-xs bg-muted px-2 py-0.5 rounded-full text-muted-foreground">
                        {platformIcon(post.platform)} {post.platform}
                      </span>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">
                      {new Date(post.publishedAt).toLocaleDateString('en-KE', { month: 'short', day: 'numeric', year: 'numeric' })}
                    </p>
                  </div>

                  {/* Metrics */}
                  <div className="flex items-center gap-5 text-sm text-muted-foreground">
                    <span className="flex items-center gap-1"><Eye className="h-3.5 w-3.5" />{formatNumber(post.views)}</span>
                    <span className="flex items-center gap-1"><Heart className="h-3.5 w-3.5" />{formatNumber(post.likes)}</span>
                    <span className="flex items-center gap-1"><MessageCircle className="h-3.5 w-3.5" />{formatNumber(post.comments)}</span>
                  </div>

                  {post.platformPostUrl && (
                    <Button variant="outline" size="sm" onClick={() => window.open(post.platformPostUrl, '_blank')}>
                      <ExternalLink className="h-4 w-4" />
                    </Button>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
